enum InventoryItem {
  yardNumber = "Yard number",
  yardName = "Yard name",
  saleDate = "Sale Date M/D/CY",
  saleTime = "Sale time (HHMM)",
  dayOfWeek = "Day of Week",
  timeZone = "Time Zone",
  itemNumber = "Item#",
  lotNumber = "Lot number",
  vehicleType = "Vehicle Type",
  bodyStyle = "Body Style",
  primaryDamage = "Damage Description",
  color = "Color",
  secondaryDamage = "Secondary Damage",
  saleTitleState = "Sale Title State",
  saleTitleType = "Sale Title Type",
  hasKeys = "Has Keys-Yes or No",
  lotCondCode = "Lot Cond. Code",
  odometer = "Odometer",
  odometerBrand = "Odometer Brand",
  retailValue = "Est. Retail Value",
  repairCost = "Repair cost",
  engine = "Engine",
  drive = "Drive",
  transmission = "Transmission",
  fuelType = "Fuel Type",
  cylinders = "Cylinders",
  runsAndDrives = "Runs/Drives",
  saleStatus = "Sale Status",
  highestBid = "High Bid =non-vix,Sealed=Vix",
  note = "Special Note",
  locationCity = "Location city",
  locationState = "Location state",
  locationZip = "Location ZIP",
  locationCountry = "Location country",
  creationDate = "Create Date/Time",
  gridRow = "Grid/Row",
  makeAnOffeAvilable = "Make-an-Offer Eligible",
  buyItNowPrice = "Buy-It-Now Price",
  currencyCode = "Currency Code",
  year = "Year",
  make = "Make",
  vin = "VIN",
  modelGroup = "Model Group",
  modelDetail = "Model Detail",
  imageThumbnail = "Image Thumbnail",
  imagesUrl = "Image URL",
  trim = "Trim",
}

export default InventoryItem;
